// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RedditDotnetScraper.Migrations
{
    [DbContext(typeof(RedditPostSqliteContext))]
    [Migration("20231008091024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("RedditCommentDto", b =>
                {
                    b.Property<string>("CommentUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCommentUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CommentUrl");

                    b.HasIndex("PostedById");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RedditPostDto", b =>
                {
                    b.Property<string>("PostUrl")
                        .HasColumnType("TEXT");

                    b.Property<long>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentsUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Upvotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostUrl");

                    b.HasIndex("PostedById");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("RedditSubredditDto", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Subreddits");
                });

            modelBuilder.Entity("RedditUserDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RedditCommentDto", b =>
                {
                    b.HasOne("RedditUserDto", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostedBy");
                });

            modelBuilder.Entity("RedditPostDto", b =>
                {
                    b.HasOne("RedditUserDto", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
